blank_issues_enabled: true
contact_links:
  - name: Shopify Partners Community 🙌
    url: https://community.shopify.com/c/partners-and-developers/ct-p/appdev
    about: Connect with Shopify and other Shopify Partners through our online communities!
